name: Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate metrics card
        uses: lowlighter/metrics@latest
        with:
          filename: assets/github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: susatwik
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Kolkata
          plugin_languages: yes
          plugin_lines: yes

